-- tblAniKind

insert into tblAniKind values( 1,1,'푸들');
insert into tblAniKind values( 2,1,'진돗개');
insert into tblAniKind values( 3,1,'말티즈');
insert into tblAniKind values( 4,1,'시츄');
insert into tblAniKind values( 5,1,'요크셔테리어');
insert into tblAniKind values( 6,1,'치와와');
insert into tblAniKind values( 7,1,'포메라니안');
insert into tblAniKind values( 8,1,'삽살개');
insert into tblAniKind values( 9,1,'시베리안 허스키');
insert into tblAniKind values( 10,1,'말티즈');
insert into tblAniKind values( 11,1,'슈나우저');
insert into tblAniKind values( 12,1,'불독');
insert into tblAniKind values( 13,1,'닥스훈트');
insert into tblAniKind values( 14,1,'비글');
insert into tblAniKind values( 15,1,'달마시안');
insert into tblAniKind values( 16,1,'리트리버');
insert into tblAniKind values( 17,2,'아메리카쇼트헤어');
insert into tblAniKind values( 18,2,'페르시안 고양이');
insert into tblAniKind values( 19,2,'메인쿤고양이');
insert into tblAniKind values( 20,2,'샴고양이');
insert into tblAniKind values( 21,2,'아비시니고양이');
insert into tblAniKind values( 22,2,'맹크스고양이');
insert into tblAniKind values( 23,2,'벵갈');
insert into tblAniKind values( 24,2,'봄베이');
insert into tblAniKind values( 25,2,'브리티시 롱헤어');
insert into tblAniKind values( 26,2,'브리티시 쇼트헤어');
insert into tblAniKind values( 27,2,'페르시안 친칠라');
insert into tblAniKind values( 28,2,'유러피안 쇼트헤어');
insert into tblAniKind values( 29,2,'코리안 숏헤어');
insert into tblAniKind values( 30,2,'맹크스');
insert into tblAniKind values( 31,2,'먼치킨');
insert into tblAniKind values( 32,2,'노르웨이숲 고양이');
insert into tblAniKind values( 33,2,'오리엔탈 롱헤어');
insert into tblAniKind values( 34,2,'오리엔탈 쇼트헤어');
insert into tblAniKind values( 35,2,'페르시안');
insert into tblAniKind values( 36,2,'랙돌');
insert into tblAniKind values( 37,2,'세렝게티');
insert into tblAniKind values( 38,2,'샴');