-- tblDis

insert into tblDis values( 1,'파보바이러스');
insert into tblDis values( 2,'슬개골 탈구');
insert into tblDis values( 3,'관절염');
insert into tblDis values( 4,'급성 췌장염');
insert into tblDis values( 5,'비만');
insert into tblDis values( 6,'요로결석');
insert into tblDis values( 7,'암');
insert into tblDis values( 8,'외이염');
insert into tblDis values( 9,'백내장');
insert into tblDis values( 10,'녹내장');
insert into tblDis values( 11,'허리디스크');
insert into tblDis values( 12,'심장질환');
insert into tblDis values( 13,'당뇨');
insert into tblDis values( 14,'심장 사상충');
insert into tblDis values( 15,'고관절 이형성');
insert into tblDis values( 16,'알레르기성 피부염');
insert into tblDis values( 17,'뇌수막염');
insert into tblDis values( 18,'노령성 심장질환');
insert into tblDis values( 19,'췌장암');
insert into tblDis values( 20,'방광염');
insert into tblDis values( 21,'구내염');
insert into tblDis values( 22,'허피스');
insert into tblDis values( 23,'범백혈구 감소증');
insert into tblDis values( 24,'칼리시 바이러스 감염증');
insert into tblDis values( 25,'클라미디아 감염증');
insert into tblDis values( 26,'백혈병바이러스');
insert into tblDis values( 27,'면역 부전 바이러스 감염증');
insert into tblDis values( 28,'전염성 복막염');
insert into tblDis values( 29,'관경병');