-- tblIngred

insert into tblIngred values(1,'4급 암모늄염+시트르산');
insert into tblIngred values(2,'Alkyldiaminoehtylglycine');
insert into tblIngred values(3,'B. bronchiseptica, P. multocida, A. pleuropneumoniae');
insert into tblIngred values(4,'BHA+에톡시퀸+구연산');
insert into tblIngred values(5,'DF-100');
insert into tblIngred values(6,'Embutramide');
insert into tblIngred values(7,'HBTA+알킬벤젠설폰산+초산');
insert into tblIngred values(8,'Maropitant Citrate');
insert into tblIngred values(9,'PED');
insert into tblIngred values(10,'Salmonella typhimurium 항혈청');
insert into tblIngred values(11,'가미스로마이신');
insert into tblIngred values(12,'가스마취기[3]');
insert into tblIngred values(13,'간균+구균+진균+효모');
insert into tblIngred values(14,'간균+셀룰로모나스균+유산균');
insert into tblIngred values(15,'간균+유산균+효모');
insert into tblIngred values(16,'간접주입용의약품주입용기구[1]');
insert into tblIngred values(17,'간질증진단용항원');
insert into tblIngred values(18,'갈릭산');
insert into tblIngred values(19,'감마글로블린');
insert into tblIngred values(20,'감초+소담즙추출물+글루타치온+셀레늄이스트');
insert into tblIngred values(21,'개 아토피성 피부염 단클론항체(Strain 34D3 Clone 15)2019-04-11');
insert into tblIngred values(22,'개 정액희석제');
insert into tblIngred values(23,'개 파보바이러스 항 면역글로블린');
insert into tblIngred values(24,'개미산');
insert into tblIngred values(25,'개미산+피리다벤');
insert into tblIngred values(26,'개별용광양자조사기[2]');
insert into tblIngred values(27,'개별용자외선조사기[2]');
insert into tblIngred values(28,'개별용적외선조사기[2]');
insert into tblIngred values(29,'개안기[1]');
insert into tblIngred values(30,'개인플루엔자');
insert into tblIngred values(31,'개파보바이러스진단용킷');
insert into tblIngred values(32,'거세기[1]');
insert into tblIngred values(33,'거치형디지털식순환기용엑스선투시진단장치[3]');
insert into tblIngred values(34,'건식임상화학자동분석장치[1]');
insert into tblIngred values(35,'검안경[1]');
insert into tblIngred values(36,'겐타마이신');
insert into tblIngred values(37,'겐타마이신+덱사메타손');
insert into tblIngred values(38,'겐타마이신+덱스트란철');
insert into tblIngred values(39,'겐타마이신+미코나졸+하이드로코르티존');
insert into tblIngred values(40,'겐타마이신+베타메타손+클로트리마졸');
insert into tblIngred values(41,'겐타마이신+설파디메톡신+트리메토프림');
insert into tblIngred values(42,'겐타마이신+설파메타진+트리메토프림');
insert into tblIngred values(43,'겐타마이신+철덱스트란+비타민B12');
insert into tblIngred values(44,'겐타마이신+치아벤다졸+덱사메타솔');
insert into tblIngred values(45,'결정성세프티오퍼유리산');
insert into tblIngred values(46,'결찰안내기[1]');
insert into tblIngred values(47,'경막외카테터[3]');
insert into tblIngred values(48,'경성관절경[2]');
insert into tblIngred values(49,'경성귀내시경[1]');
insert into tblIngred values(50,'경성복강경[2]');
insert into tblIngred values(51,'경성인두경[1]');
insert into tblIngred values(52,'경피혈중가스분석기[2]');
insert into tblIngred values(53,'계두');
insert into tblIngred values(54,'고강도집속형초음파수술기[3]');
insert into tblIngred values(55,'고나도레닌');
insert into tblIngred values(56,'고나도트로핀+비타민 E');
insert into tblIngred values(57,'고메놀+구아이아콜+유칼립톤+캠퍼+아이도폼+에페드린');
insert into tblIngred values(58,'고삼추출물(매트린)');
insert into tblIngred values(59,'고양이 FIP 백신');
insert into tblIngred values(60,'고양이 백혈병바이러스');
insert into tblIngred values(61,'고양이범백혈구감소증바이러스 고양이허피스바이러스 고양이칼리시바이러스');
insert into tblIngred values(62,'고양이전염성복막염진단킷트');
insert into tblIngred values(63,'고위험성동물전염병면역검사시약[3]');
insert into tblIngred values(64,'고위험성동물전염병유전검사용시약[3]');
insert into tblIngred values(65,'고정형디지탈형엑스선진단투시촬영장치[3]');
insert into tblIngred values(66,'고주파열상발생기[3]');
insert into tblIngred values(67,'골겸자[1]');
insert into tblIngred values(68,'골접합용나사[3]');
insert into tblIngred values(69,'골접합용와이어[3]');
insert into tblIngred values(70,'골접합용판[3]');
insert into tblIngred values(71,'과산화벤조일');
insert into tblIngred values(72,'과산화수소');
insert into tblIngred values(73,'과산화수소+과초산');
insert into tblIngred values(74,'과산화수소+은');
insert into tblIngred values(75,'관리무통법용수액펌프[3]');
insert into tblIngred values(76,'관장기[1]');
insert into tblIngred values(77,'광견');
insert into tblIngred values(78,'광견병');
insert into tblIngred values(79,'광물질공급약');
insert into tblIngred values(80,'광합성세균농축배양물');
insert into tblIngred values(81,'구강개구기[1]');
insert into tblIngred values(82,'구강용카메라[1]');
insert into tblIngred values(83,'구리+아미노산');
insert into tblIngred values(84,'구리염화물');
insert into tblIngred values(85,'구리푸로틴네이트');
insert into tblIngred values(86,'구리프로티네이트');
insert into tblIngred values(87,'구아이페네신');
insert into tblIngred values(88,'구아이페네신+염화암모늄+요오드화칼륨');
insert into tblIngred values(89,'구아이페네신+주석산타이로신+록시스로마이신');
insert into tblIngred values(90,'구연산 자몽종자추출물');
insert into tblIngred values(91,'구연산+말릭산+인산');
insert into tblIngred values(92,'구연산+젖산');
insert into tblIngred values(93,'구제역');
insert into tblIngred values(94,'구중청량제');
insert into tblIngred values(95,'국소지혈용품[2]');
insert into tblIngred values(96,'귀세정용 탈지면');
insert into tblIngred values(97,'귀세척제');
insert into tblIngred values(98,'귀적외선체온계[2]');
insert into tblIngred values(99,'그리세오풀빈');
insert into tblIngred values(100,'글래서병+마이코플라즈마폐렴');