-- tblProduct

SET ESCAPE ON;
SHOW ESCAPE;

insert into tblProduct values(1,'아쿠아 팜세이프(Aqua farmsafe)');
insert into tblProduct values(2,'노프러블럼액');
insert into tblProduct values(3,'대성 가이드크린 액(DS Guideclean Liq.)');
insert into tblProduct values(4,'하나텐(Hanaten)');
insert into tblProduct values(5,'웰크린-씨(Wellclin-C)');
insert into tblProduct values(6,'팜닥터');
insert into tblProduct values(7,'잡스애니케어플러스(ZAPSANICAREPLUS)');
insert into tblProduct values(8,'쎄탁-큐(CETAK-Q)');
insert into tblProduct values(9,'태고-SP(Tego-SP)');
insert into tblProduct values(10,'트리콤 플러스(Tricom Plus)');
insert into tblProduct values(11,'인테독스-디(INTEDOX-D)');
insert into tblProduct values(12,'키롤첨가제(KILOL POWER)');
insert into tblProduct values(13,'시트러스파우더(CITRUS POWDER)');
insert into tblProduct values(14,'디에프60(DF 60)');
insert into tblProduct values(15,'시트러스유방연고(CITRUS UDDER OINTMENT)');
insert into tblProduct values(16,'우성바이오클린');
insert into tblProduct values(17,'키롤액(KILOL LIQUID)');
insert into tblProduct values(18,'키롤액-양어용(KILOL LIQUID-FISH)');
insert into tblProduct values(19,'그린백(GREEN 100)');
insert into tblProduct values(20,'티-61(T-61)');
insert into tblProduct values(21,'스트롱존');
insert into tblProduct values(22,'핀바이러스(FINVIRUS)');
insert into tblProduct values(23,'세레니아 주사액(Cerenia Solution for Injection for dogs and cats)');
insert into tblProduct values(24,'세레니아 정(Cerenia Tablet)');
insert into tblProduct values(25,'힘백 돈사방-PED 투플러스 주(수출용)(Himmvac Donsaban-PED++ Inactivated Vaccine)');
insert into tblProduct values(26,'프로백 피이디-에프씨(II) 주(PRO-VAC PED-Fc(II))');
insert into tblProduct values(27,'이뮤니스 피이디-엠(돼지유행성설사병백신)(Immunis PED-M)');
insert into tblProduct values(28,'셉티시럼');
insert into tblProduct values(29,'작트란-주(가미스로마이신)(Zactran)');
insert into tblProduct values(30,'가스마취기[3](CDS2000 Small Animal Anesthesia)');
insert into tblProduct values(31,'가스마취기[3](University Anesthesia Machine)');
insert into tblProduct values(32,'가스마취기[3](CWM-101A VET Anesthesia Machine)');
insert into tblProduct values(33,'가스마취기[3](AM852 VET Anesthesia Machine)');
insert into tblProduct values(34,'가스마취기[3](R620IP VET Anesthesia Machine)');
insert into tblProduct values(35,'가스마취기[3](AM852)');
insert into tblProduct values(36,'살지우-젠');
insert into tblProduct values(37,'엔비로골드(EnviroGold)');
insert into tblProduct values(38,'대성 클리너 산(DS CLEANER Powder)');
insert into tblProduct values(39,'엔비슈퍼100(NB SUPER 100)');
insert into tblProduct values(40,'스프락-P(Sfrac-P)');
insert into tblProduct values(41,'바이오슈퍼-86(BIO.SUPER-86)');
insert into tblProduct values(42,'월드랩스');
insert into tblProduct values(43,'디오스-A(DeOS-A)');
insert into tblProduct values(44,'간접주입용동물용의약품주입용기구[1](TX-1016외 4종)');
insert into tblProduct values(45,'간접주입용의약품주입용기구[1](D-Grip Tube Holder)');
insert into tblProduct values(46,'간접주입용의약품 주입용기구[1](Dosing Device 32/35 ppp)');
insert into tblProduct values(47,'간접주입용의약품주입용기구[1](머다알약투약기(MD-100),알약투약기(MD-100))');
insert into tblProduct values(48,'소간질진단액');
insert into tblProduct values(49,'G-1000');
insert into tblProduct values(50,'GC-200(GC-200)');
insert into tblProduct values(51,'수이감민');
insert into tblProduct values(52,'파우글로블린');
insert into tblProduct values(53,'수이글로빈');
insert into tblProduct values(54,'감마세린');
insert into tblProduct values(55,'보비글로빈');
insert into tblProduct values(56,'대성 감마글로블린주');
insert into tblProduct values(57,'대성액상감마주');
insert into tblProduct values(58,'동물용(우.돈.견)감마글로브린');
insert into tblProduct values(59,'돼지용 감마글로블린주(SWINE GAMMA GLOBULIN INJECTION)');
insert into tblProduct values(60,'견용 감마글로블린-주(CANINE GAMMA GLOBULIN INJECTION)');
insert into tblProduct values(61,'하이프로텍트(HIPROTECT)');
insert into tblProduct values(62,'코미감마글로부린(KOMI GAMMA GLOBULIN INJ.)');
insert into tblProduct values(63,'모톤-G(MOTON-G)');
insert into tblProduct values(64,'동물용(우.돈.견)감마글로브린');
insert into tblProduct values(65,'헤드스타트');
insert into tblProduct values(66,'아쿠아헤파민(수산용)(AQUA HEPAMIN)');
insert into tblProduct values(67,'사이토포인트 주(CYTOPOINT)');
insert into tblProduct values(68,'케니플러스 프리즈 액(CaniPlus Freeze)');
insert into tblProduct values(69,'케니플러스 인핸스(CaniPlus Enhance)');
insert into tblProduct values(70,'캔글로브 P(Canglob P)');
insert into tblProduct values(71,'응애멸(EUNGEMEUL)');
insert into tblProduct values(72,'바이오애드');
insert into tblProduct values(73,'마이트-K');
insert into tblProduct values(74,'와구프리(Wagoo-Free)');
insert into tblProduct values(75,'개별용광양자조사기[2](BEP-AN11)');
insert into tblProduct values(76,'개별용광양자조사기[2](Photonia-AN17)');
insert into tblProduct values(77,'개별용자외선조사기[2](Ray-Vet)');
insert into tblProduct values(78,'개별용적외선조사기[2](SUPER LIZER 2200LITE)');
insert into tblProduct values(79,'개안기[1](270610)');
insert into tblProduct values(80,'캐니플루-맥스(CaniFlu-max)');
insert into tblProduct values(81,'프로-체크 씨피브이 래피드 킷트(Pro-check CPV Rapid Kit)');
insert into tblProduct values(82,'이지캡처 개 파보바이러스 원스텝 검사킷트');
insert into tblProduct values(83,'거세기[1](200066외 22종)');
insert into tblProduct values(84,'거세기[1](TX-411외 7종)');
insert into tblProduct values(85,'거세기[1](NFE 50외 3종)');
insert into tblProduct values(86,'동물 거치형디지털식순환기용엑스선투시진단장치[3](Artis Zee Multi-purpose)');
insert into tblProduct values(87,'건식임상화학자동분석장치 [1]((VetTest 8008 Clinical Chemistry))');
insert into tblProduct values(88,'건식임상화학자동분석장치 [1]((IDEXX Catalyst Dx))');
insert into tblProduct values(89,'건식임상화학자동분석장치[1](IDEXX Catalyst ONE)');
insert into tblProduct values(90,'건식임상화학자동분석장치[1](VetScan VUE Rapid Test Reader)');
insert into tblProduct values(91,'동물의료용건식임상화학자동분석장치[1](Fiji DRI-CHEM 4000ie)');
insert into tblProduct values(92,'동물의료용건식임상화학자동분석장치[1](FUJI DRI-CHEM 7000i)');
insert into tblProduct values(93,'동물의료용건식임상화학자동분석장치[1](FUJI DRI-CHEM NX500i)');
insert into tblProduct values(94,'건식임상화학자동분석장치[1](FUJI DRI-CHEM NX500V IC)');
insert into tblProduct values(95,'건식임상화학자동분석장치(SMT-100V)');
insert into tblProduct values(96,'건식임상화학자동분석장치[1](SPOTCHEM EZ SP 4430)');
insert into tblProduct values(97,'동물의료용건식임상화학자동분석장치[1](SPOTCHEM™ EZ SP-4430)');
insert into tblProduct values(98,'동물의료용건식임상화학자동분석장치[1](PocketChem™ BA PA-4140)');
insert into tblProduct values(99,'건식임상화학자동분석장치[1](solo)');
insert into tblProduct values(100,'건식임상화학자동분석장치[1](GVT-100)');
insert into tblProduct values(101,'검안경[1](UR-9000 Vet Modular Diagnostic System)');
insert into tblProduct values(102,'검안경[1](Ophthalmodiastimeter, 270110외 2종)');
insert into tblProduct values(103,'신일겐타마이신주(GENTAMICIN INJECTION)');
insert into tblProduct values(104,'겐타마이신-100주(GENTAMICIN-100 INJECTION)');
insert into tblProduct values(105,'게로신(수출용)(GEROCIN)');
insert into tblProduct values(106,'진우겐타마이신');
insert into tblProduct values(107,'겐타-50주');
insert into tblProduct values(108,'대성 겐타마이신 주');
insert into tblProduct values(109,'대성아카마이신15%주사(D.S. AKAMYCIN 15% INJ.)');
insert into tblProduct values(110,'대성겐타마이신10%주사');
insert into tblProduct values(111,'키토겐(수출용)');
insert into tblProduct values(112,'녹수 겐타마이신-주(GENTAMYCIN)');
insert into tblProduct values(113,'푸른바다 겐타신');
insert into tblProduct values(114,'삼우 겐타 주사(SAM U GENTA INJECTION)');
insert into tblProduct values(115,'겐타엘에이 주사(GENTA LA INJECTION)');
insert into tblProduct values(116,'삼우 겐타마이신-15주사(SAMU GENTAMICIN-15 INJECTION)');
insert into tblProduct values(117,'삼우 겐타마이신 주사(Samu Gentamicin Injection)');
insert into tblProduct values(118,'이글 겐타마이신(주)(Eagle Gentamycin Inj.)');
insert into tblProduct values(119,'이글겐타마이신10(주)(수출용)');
insert into tblProduct values(120,'겐타-비 (주)(Genta-B Inj.)');
insert into tblProduct values(121,'SF 겐타마이신(SF GENTAMICIN)');
insert into tblProduct values(122,'겐타산 20');
insert into tblProduct values(123,'겐타피그(GENTAPIG)');
insert into tblProduct values(124,'겐타잘 주 100㎎(수출용, 겐타마이신)(Gentasal 100 Inj.)');
insert into tblProduct values(125,'코미겐타마이신 50주');
insert into tblProduct values(126,'썸벧 겐타마이신 수용산(수출용)');
insert into tblProduct values(127,'수산용 겐타휘쉬');
insert into tblProduct values(128,'썸벧 겐타마이신주사(수출용)');
insert into tblProduct values(129,'동방겐타맥스LA(Gentamax LA)');
insert into tblProduct values(130,'겐타세라피50주(수출용)');
insert into tblProduct values(131,'겐타세라피 100주(수출용)');
insert into tblProduct values(132,'오티벳(OTIVET)');
insert into tblProduct values(133,'에스마이신(s-mycin)');
insert into tblProduct values(134,'겐타솔루션(Genta Solution)');
insert into tblProduct values(135,'에스겐타마이신플러스');
insert into tblProduct values(136,'수출용 겐타포스산(겐타마이신황산염)(Genta-force)');
insert into tblProduct values(137,'대성 겐타마이신크림(주입제)');
insert into tblProduct values(138,'겐타손 스프레이(수출용)(GENTASON SPRAY)');
insert into tblProduct values(139,'오토맥스(OTOMAX)');
insert into tblProduct values(140,'덱스페론-G 주(Dexferron-G inj.)');
insert into tblProduct values(141,'대성 겐타철 주');
insert into tblProduct values(142,'키토철(수출용)');
insert into tblProduct values(143,'겐타론-B 주사(수출용)');
insert into tblProduct values(144,'아이론-겐타(IRON GENTA)');
insert into tblProduct values(145,'겐타덱스20(수출용)(GENTADEX-20)');
insert into tblProduct values(146,'이소틱(Easotic)');
insert into tblProduct values(147,'트라이오틱(Tri-Otic Ointment)');
insert into tblProduct values(148,'오리모덤(AURIMODERM)');
insert into tblProduct values(149,'겐타-티.에스.(수출용)(GENTA-T.S.)');
insert into tblProduct values(150,'겐타-설주(수출용)(GENTA SUL INJ)');
insert into tblProduct values(151,'겐타페론(수출용)(Gentaferron)');
insert into tblProduct values(152,'덱소릴(DEXORYL)');
insert into tblProduct values(153,'엑센트 플러스 현탁주(Accent Plus Suspension)');
insert into tblProduct values(154,'아반떼 플러스(Avante plus injection)');
insert into tblProduct values(155,'세프론세븐(CEFRON SEVEN)');
insert into tblProduct values(156,'세프레스 현탁주 100mg(결정성세프티오퍼유리산)(CefRes Inj.)');
insert into tblProduct values(157,'셉티퍼 현탁주(CEFTIFUR injectable suspension)');
insert into tblProduct values(158,'팍셀포르테(Paxxcel forte)');
insert into tblProduct values(159,'세레스탑-LA(Cerestop-LA)');
insert into tblProduct values(160,'세프림 LA 주(Cefrim LA inj)');
insert into tblProduct values(161,'프라임샷(Prime shot)');
insert into tblProduct values(162,'세디움 LA(수출용)(Cedium LA)');
insert into tblProduct values(163,'프레림 양돈용(Prellim for swine)');
insert into tblProduct values(164,'낙셀 엘에이(Naxcel LA)');
insert into tblProduct values(165,'세프롱 샷(Ceflong shot)');
insert into tblProduct values(166,'결찰안내기[1](140780)');
insert into tblProduct values(167,'결찰안내기[1](Crimp plier 415.1001)');
insert into tblProduct values(168,'경막외카테터[3](SE-15-V 외 1종)');
insert into tblProduct values(169,'경성관절경[2](AR-3350-5030 외 20종)');
insert into tblProduct values(170,'경성귀내시경[1](DE 501)');
insert into tblProduct values(171,'경성귀내시경[1](DE 551)');
insert into tblProduct values(172,'경성귀내시경[1](DE 551)');
insert into tblProduct values(173,'경성복강경[2](PE590A외 3종)');
insert into tblProduct values(174,'경성복강경[2](63005AA 외 56종)');
insert into tblProduct values(175,'경성복강경[2](Laparoscope 61015 BV외 28종)');
insert into tblProduct values(176,'경성복강경[2](AR-3351-5500 외 7종)');
insert into tblProduct values(177,'경성인두경[1](DE 1250)');
insert into tblProduct values(178,'경피혈중가스분석기[2](V9004 Capnograph Monitors)');
insert into tblProduct values(179,'경피혈중가스분석기[2](V9400 Anesthetic Agent Monitor)');
insert into tblProduct values(180,'힘백 계두 백신(HIMMVAC FOWL POX VACCINE)');
insert into tblProduct values(181,'대성 계두 치큰백');
insert into tblProduct values(182,'포울샷 계두(PoulShot Pox)');
insert into tblProduct values(183,'계두백신주(수출용)(AVIAN FOWL POX VACCINE)');
insert into tblProduct values(184,'프로백 계두(PRO-VAC FP)');
insert into tblProduct values(185,'고강도집속형초음파수술기[3](VIFU 2000)');
insert into tblProduct values(186,'고나신-주(GONASHIN-INJ.)');
insert into tblProduct values(187,'오부레린(Ovurelin)');
insert into tblProduct values(188,'고나린 주사(고나도레린)');
insert into tblProduct values(189,'오뷰란(수출용)(Ovuran)');
insert into tblProduct values(190,'고나돈');
insert into tblProduct values(191,'고도렐(GODOREL)');
insert into tblProduct values(192,'씨스토레린(CYSTORELIN)');
insert into tblProduct values(193,'펙트렐 주사(고나도렐린)(FACTREL INJ.)');
insert into tblProduct values(194,'고나실(GONASYL)');
insert into tblProduct values(195,'페르틸린(FERTILINE)');
insert into tblProduct values(196,'훠타길(FERTAGYL)');
insert into tblProduct values(197,'한벳-고나레린 주(HANVET-GONARELIN inj.)');
insert into tblProduct values(198,'오바레린(OVARELIN)');
insert into tblProduct values(199,'프로란-이 주사액(PROLAN-E OILY SOLUTION)');
insert into tblProduct values(200,'네오발사미코(주사액)');
insert into tblProduct values(201,'퓨오 에코킬 유제(Fuo EcoKill EC)');
insert into tblProduct values(202,'펠로셀 에프아이피(Felocell FIP)');
insert into tblProduct values(203,'펠로셀 FeLV주 (고양이 백혈병바이러스 백신)(Felocell FeLV)');
insert into tblProduct values(204,'펠리샷 피에이치씨(FeliShot PHC)');
insert into tblProduct values(205,'펠로셀 4(Felocell 4)');
insert into tblProduct values(206,'프로-체크 에프씨브이 에이지 래피드 킷트(Pro-check FCV Ag Rapid Kit)');
insert into tblProduct values(207,'고위험성동물전염병면역검사시약[3](Speed Diro/Heartworm)');
insert into tblProduct values(208,'고위험성동물전염병면역검사시약[3](SERELISA PRV g1 Ab Mono Blocking)');
insert into tblProduct values(209,'고위험성동물전염병면역검사시약[3](IDEXX PRV/ADV gI Ab Test)');
insert into tblProduct values(210,'고위험성동물전염병면역검사시약[3](IDEXX IBD-XR Ab Test)');
insert into tblProduct values(211,'고위험성동물전염병면역검사시약[3](IDEXX IBV Ab Test kit)');
insert into tblProduct values(212,'고위험성동물전염병면역검사시약[3](IDEXX MG/MS Ab Test kit)');
insert into tblProduct values(213,'고위험성동물전염병면역검사시약[3](IDEXX cELISA EIA Test kit)');
insert into tblProduct values(214,'고위험성동물전염병면역검사시약[3](IDEXX SE Ab Test kit)');
insert into tblProduct values(215,'고위험성동물전염병면역검사시약[3](IDEXX Paratuberculosis Screening Ab Test kit)');
insert into tblProduct values(216,'고위험성동물전염병면역검사시약[3](IDEXX BVDV Ag/Serum Plus)');
insert into tblProduct values(217,'고위험성동물전염병면역검사시약[3](IDEXX PRRS X3 Ab Test kit)');
insert into tblProduct values(218,'고위험성동물전염병면역검사시약[3](Vetscan VS2 Canine Wellness Profile)');
insert into tblProduct values(219,'고위험성동물전염병면역검사시약[3]((Solo Step CH))');
insert into tblProduct values(220,'고위험성동물전염병면역검사시약[3]((Solo Step FH))');
insert into tblProduct values(221,'고위험성동물전염병면역검사시약[3](BIONOTE FMDV NSP Ab ELISA)');
insert into tblProduct values(222,'고위험성동물전염병면역검사시약[3](Anigen Rapid Canine Heartworm Ag Test Kit 2.0)');
insert into tblProduct values(223,'고위험성동물전염병면역검사시약[3]((Anigen Rapid Feline Heartworm Ab Test Kit))');
insert into tblProduct values(224,'고위험성동물전염병면역검사시약[3]((Anigen Rapid Anaplasma Ab Test Kit(수출용)))');
insert into tblProduct values(225,'고위험성동물전염병면역검사시약[3]((BIONOTE PRRS Ab ELISA 4.0))');
insert into tblProduct values(226,'고위험성동물전염병면역검사시약 [3](Anigen Rapid IBDV Ag Test Kit)');
insert into tblProduct values(227,'고위험성동물전염병면역검사시약[3](BIONOTE CSFV Ab B-ELISA)');
insert into tblProduct values(228,'고위험성동물전염병면역검사시약 [3]((Anigen Rapid TGE Ag Test Kit))');
insert into tblProduct values(229,'고위험성동물전염병면역검사시약 [3](Anigen Rapid IBV Ag Test Kit(수출 전용))');
insert into tblProduct values(230,'고위험성동물전염병면역검사시약[3](BIONOTE IBV Ab ELISA)');
insert into tblProduct values(231,'고위험성동물전염병면역검사시약[3](BIONOTE IBDV Ab ELISA)');
insert into tblProduct values(232,'고위험성동물전염병면역검사시약[3](BIONOTE CSFV Ab I-ELISA)');
insert into tblProduct values(233,'고위험성동물전염병면역검사시약[3](Anigen Rapid FMD NSP Ab Test Kit, 수출용)');
insert into tblProduct values(234,'고위험성동물전염병면역검사시약[3](Anigen Rapid PED/TGE/ROTA Ag Test Kit,수출용)');
insert into tblProduct values(235,'동물전염병면역검사시약[3](Vcheck CHW Ag)');
insert into tblProduct values(236,'고위험성동물전염병면역검사시약[2](Anigen Rapid FHW Ag/Ab Test Kit, 수출용)');
insert into tblProduct values(237,'고위험성동물전염병면역검사시약[3](Anigen Rapid ASFV Ag Test Kit, 수출용)');
insert into tblProduct values(238,'고위험성동물전염병면역검사시약[3](ID Screen Paratuberculosis Indirect)');
insert into tblProduct values(239,'고위험성동물전염병면역검사시약[3](ID Screen Bluetongue Competition)');
insert into tblProduct values(240,'고위험성동물전염병면역검사시약[3](ID Screen African Swine Fever Indirect Screening test)');
insert into tblProduct values(241,'고위험성동물전염병면역검사시약(3)(PrioCHECK FMDV Type O Antibody Detection Kit)');
insert into tblProduct values(242,'고위험성동물전염병면역검사시약[3](Asan Easy Test Heartworm)');
insert into tblProduct values(243,'고위험성동물전염병면역검사시약[3](Infectious Bronchitis Virus Antibody Test Kit(닭 전염성기관지염 항체검사 키트))');
insert into tblProduct values(244,'고위험성동물전염병면역검사시약 [3](VDPro CSFV AB ELISA)');
insert into tblProduct values(245,'고위험성동물전염병면역검사시약［3］(VDPro CSFV AB C-ELISA [3])');
insert into tblProduct values(246,'고위험성동물전염병면역검사시약［3］(VDPro CSFV AG ELISA [3])');
insert into tblProduct values(247,'고위험성동물전염병면역검사시약［3］(VDPro FMDV NSP AB ELISA)');
insert into tblProduct values(248,'고위험성동물전염병면역검사시약［3］(VDPro FMDV Type O ELISA)');
insert into tblProduct values(249,'고위험성동물전염병면역검사시약［3］(VDPro BVDV AB ELISA)');
insert into tblProduct values(250,'고위험성동물전염병면역검사시약［3］(VDPro CSFV Marker AB ELISA)');
insert into tblProduct values(251,'고위험성동물전염병면역검사시약［3］(VDPro IBDV AB ELISA)');
insert into tblProduct values(252,'고위험성동물전염병면역검사시약［3］(VDPro IBV AB ELISA)');
insert into tblProduct values(253,'고위험성동물전염병면역검사시약［3］(VDPro MG AB ELISA)');
insert into tblProduct values(254,'고위험성동물전염병면역검사시약［3］(VDPro MS AB ELISA)');
insert into tblProduct values(255,'고위험성동물전염병면역검사시약［3］(VDPro MG/MS AB ELISA)');
insert into tblProduct values(256,'고위험성동물전염병면역검사시약［3］(VDPro PRRSV VR AB ELISA)');
insert into tblProduct values(257,'고위험성동물전염벼면역검사시약［3］(VDPro IBDV AGID)');
insert into tblProduct values(258,'고위험성동물전염병면역검사시약［3］(VDPro ADV gI AB ELISA)');
insert into tblProduct values(259,'고위험성동물전염병면역검사시약［3］(VDPro ADV AB Screen ELISA)');
insert into tblProduct values(260,'고위험성동물전염병면역검사시약［3］(VDPro AIV-NDV-IBV AB Triple ELISA)');
insert into tblProduct values(261,'고위험성동물전염병면역검사시약［3］((VDPro FMDV Type A AB ELISA) (수출용))');
insert into tblProduct values(262,'고위험성동물전염병면역검사시약［3］(VDPro FMDV Type Asia1 AB ELISA(수출용))');
insert into tblProduct values(263,'고위험성동물전염병면역검사시약[3］((VDPro PRRSV AB ELISA)(수출용))');
insert into tblProduct values(264,'고위험성동물전염병면역검사시약[3](VDRG CHW Ag Rapid Kit)');
insert into tblProduct values(265,'고위험성동물전염병면역검사시약[3](VDPro ADV FA Reagent)');
insert into tblProduct values(266,'고위험성동물전염병면역검사시약[3](VDPro CSFV FA Reagent)');
insert into tblProduct values(267,'고위험성동물전염병면역검사시약[3](VDPro PRRSV FA Reagent)');
insert into tblProduct values(268,'고위험성동물전염병면역검사시약[3](VDPro TGEV FA Reagent)');
insert into tblProduct values(269,'고위험성동물전염병면역검사시약[3](VDRG BLV Ab Rapid Kit)');
insert into tblProduct values(270,'고위험성동물전염병면역검사시약[3](VDPro BLV AGID Reagent)');
insert into tblProduct values(271,'고위험성동물전염병면역검사시약[3](VDPro Bovine Leukosis Ab b-ELISA)');
insert into tblProduct values(272,'고위험성동물전염병면역검사시약[3](VDRG FMDV 3Diff/PAN Ag Rapid kit)');
insert into tblProduct values(273,'고위험성동물전염병면역검사시약[3](VDPro CSFV Ab c-ELISA)');
insert into tblProduct values(274,'고위험성동물전염병면역검사시약[3](VDPro CSFV Erns Ab b-ELISA)');
insert into tblProduct values(275,'고위험성동물전염병면역검사시약[3](VDPro FMDV Type O Ab b-ELISA)');
insert into tblProduct values(276,'고위험성동물전염병면역검사시약[3](VDPro BVDV Erns Ab i-ELISA)');
insert into tblProduct values(277,'고위험성동물전염병면역검사시약[3](SensPERT Canine Heartworm test kit)');
insert into tblProduct values(278,'고위험성동물전염병면역검사시약[3](SensPERT Anaplasma phagocytophilum Ab test kit)');
insert into tblProduct values(279,'고위험성동물전염병면역검사시약[3](SensPERT Anaplasma/Ehrlichia canis Ab combo test kit)');
insert into tblProduct values(280,'고위험성동물전염병면역검사시약[3](SensPERT Feline Heartworm Ag Test kit, 수출용)');
insert into tblProduct values(281,'고위험성동물전염병면역검사시약[3](SensPERT Canine Heartworm Ag/Anaplasma Ab/E.canis Ab/LSH Ab Test Kit, 수출용)');
insert into tblProduct values(282,'고위험성동물전염병면역검사시약[3](SensPERT Feline Heartworm Ag/Feline Leukemia virus Ag/Feline Immunodeficiency virus Ab, 수출용)');
insert into tblProduct values(283,'고위험성동물전염병면역검사시약[3](SensPERT Canine Heartworm Ag/Anaplasma Ab/E.canis Ab/Lyme Ab Test Kit, 수출용)');
insert into tblProduct values(284,'고위험성동물전염병면역검사시약[3](SensPERT Canine Babesia gibsoni Ab Test kit, 수출용)');
insert into tblProduct values(285,'고위험성동물전염병면역검사시약 [3](RapiGEN CHW Ag TEST,RapiGEN CHW Ag TEST Multi, GREENGEN CHW Ag TEST)');
insert into tblProduct values(286,'고위험성동물전염병면역검사시약[3](CIVTEST SUIS ADVgB)');
insert into tblProduct values(287,'추백리진단시약(Purullum diagnostic tester)');
insert into tblProduct values(288,'고위험성동물전염병면역검사시약[3](대성 추백리 진단액)');
insert into tblProduct values(289,'고위험성동물전염병면역검사시약[3](Pro-Check CHW Ag Rapid Kit)');
insert into tblProduct values(290,'고위험성동물전염병면역검사시약[3]((PAD-Kit))');
insert into tblProduct values(291,'고위험성동물전염병면역검사시약[3](PrioCHECK FMDV type O)');
insert into tblProduct values(292,'고위험성동물전염병면역검사시약[3](AnyLab CHW Ag Test)');
insert into tblProduct values(293,'고위험성동물전염병면역검사시약[3]((BIT Rapid color CHW))');
insert into tblProduct values(294,'고위험성동물전염병면역검사시약[3](LiliF Infectious Bursal Disease Virus Ag Rapid Kit(수출전용))');
insert into tblProduct values(295,'고위험성동물전염병면역검사시약[3](bionet BVDV Ag kit)');
insert into tblProduct values(296,'고위험성동물전염병면역검사시약[3](Bionet TGEV Ag Rapid kit, 수출용)');
insert into tblProduct values(297,'고위험성동물전염병면역검사시약[3](Bionet PEDV/TGEV/Rota Ag Rapid kit, 수출용)');
insert into tblProduct values(298,'고위험성동물전염병면역검사시약[3](GenBody CHW Ag,수출용)');
insert into tblProduct values(299,'고위험성동물전염병면역검사시약[3](ADx BVD AB ELISA)');
insert into tblProduct values(300,'고위험성동물전염병면역검사시약[3](ADx CSF AB ELISA)');
insert into tblProduct values(301,'고위험성동물전염병면역검사시약[3](ADx CSF AG ELISA)');
insert into tblProduct values(302,'고위험성동물전염병면역검사시약[3](ADx FMD NSP AB ELISA)');
insert into tblProduct values(303,'고위험성동물전염병면역검사시약[3](ADx FMD Type A AB ELISA)');
insert into tblProduct values(304,'고위험성동물전염병면역검사시약[3](ADx FMD Type Asia1 AB ELISA)');
insert into tblProduct values(305,'고위험성동물전염병면역검사시약[3](ADx FMD Type O AB ELISA)');
insert into tblProduct values(306,'고위험성동물전염병면역검사시약[3](ADx PRV/ADV gB AB ELISA)');
insert into tblProduct values(307,'고위험성동물전염병면역검사시약[3](ADx PRV/ADV gI AB ELISA)');
insert into tblProduct values(308,'고위험성동물전염병유전검사용시약[3](AccuPower FMDV Real-time RT-PCR MasterMix kit)');
insert into tblProduct values(309,'고위험성동물전염병유전검사용시약[3](AccuPower Bacterial Poultry 3-Plex PCR Kit)');
insert into tblProduct values(310,'고위험성동물전염병유전검사용시약[3](AccuPower Babesia PCR Kit (BAB-1115P))');
insert into tblProduct values(311,'고위험성동물전염병유전검사용시약[3](AccuPower Babesia & Theileria PCR Kit (BNT-1115P))');
insert into tblProduct values(312,'고위험성동물전염병유전검사용시약[3](AccuPower Theileria PCR Kit (THE-1115P))');
insert into tblProduct values(313,'고위험성동물전염병유전검사용시약[3](ID Gene African Swine Fever Duplex)');
insert into tblProduct values(314,'고위험성동물전염병유전검사용시약[3](VDx PRRSV ORF7 RT-PCR)');
insert into tblProduct values(315,'고위험성동물전염병유전검사용시약［3］(VDx CSFV 5‘NCR RT-PCR)');
insert into tblProduct values(316,'고위험성동물전염병유전검사용시약[3］(VDx PRRSV NA/EU Typing Nested PCR)');
insert into tblProduct values(317,'고위험성동물전염병유전검사용시약[3］(VDx PRRSV HP MP RT-PCR)');
insert into tblProduct values(318,'고위험성동물전염병유전검사용시약[3](VDx Fowl Typhoid Dif PCR)');
insert into tblProduct values(319,'고위험성동물전염병유전자검사용시약[3](VDx Abortion MP PCR)');
insert into tblProduct values(320,'고위험성동물전염병유전검사용시약[3](AnyQ CSFV qRT-PCR, VDx CSFV qRT-PCR)');
insert into tblProduct values(321,'고위험성동물전염병유전검사용시약[3](VDX ASFV qPCR)');
insert into tblProduct values(322,'고위험성동물전염병유전검사시약[3](VDx PRRSV qRT-PCR, AnyQ PRRSV qRT-PCR)');
insert into tblProduct values(323,'고위험성동물전염병유전검사용시약[3](VDx ASFV/CSFV qRT-PCR, 수출용)');
insert into tblProduct values(324,'수출용 고위험성동물전염병유전검사용시약[3］(VDX ASFV LAMP, 수출용)');
insert into tblProduct values(325,'고위험성동물전염병유전검사용시약[3](VDx CEM qPCR)');
insert into tblProduct values(326,'고위험성동물전염병유전검사시약[3](VDx PRRSV/PCV2 qRT-PCR)');
insert into tblProduct values(327,'고위험성동물전염병유전검사용시약[3](VDx FMDV qRT-PCR)');
insert into tblProduct values(328,'고위험성동물전염병유전검사용시약[3](VDx FMDV A qRT-PCR, 수출용)');
insert into tblProduct values(329,'고위험성동물전염병유전검사용시약[3](VDx FMDV Asia1 qRT-PCR, 수출용)');
insert into tblProduct values(330,'고위험성동물전염병유전검사용시약[3](VDx FMDV O qRT-PCR, 수출용)');
insert into tblProduct values(331,'고위험성동물전염병유전검사용시약[3](LiliF BD-Multi RT-PCR Kit)');
insert into tblProduct values(332,'고위험성동물전염병유전검사용시약[3](LiliF BD-Multi RT-PCR Kit(PART I & II))');
insert into tblProduct values(333,'고위험성동물전염병유전검사용시약[3](LiliF TGEV_PEDV RT-PCR Kit)');
insert into tblProduct values(334,'고위험성동물전염병유전검사용시약[3](LiliF TGEV/PEDV RT-PCR Kit(PART I & II))');
insert into tblProduct values(335,'고위험성동물전염병유전검사용시약[3](LiliF BVDV RT-PCR Kit)');
insert into tblProduct values(336,'고위험성동물전염병유전검사용시약[3](PowerChekTM PRRSV EU/NA Real-time PCR Kit(수출전용))');
insert into tblProduct values(337,'고위험성동물전염병유전검사용시약[3](PowerChekTM Bovine Disease Virus Triplex Real-time PCR Kit)');
insert into tblProduct values(338,'고위험성동물전염병유전검사용시약[3](PowerChekTM BVDV Real-time PCR Kit)');
insert into tblProduct values(339,'고위험성동물전염병유전검사용시약[3](PowerChekTM Mycoplasma gallisepticum / Mycoplasma synoviae Real-time PCR Kit)');
insert into tblProduct values(340,'고위험성동물전염병유전검사용시약[3](PowerChekTM PEDV / TGEV Real-time PCR kit)');
insert into tblProduct values(341,'고위험성동물전염병유전검사용시약[3](PowerChek PRRSV/PCV2 Multiplex Real-time PCR Kit)');
insert into tblProduct values(342,'고위험성전염병유전검사용시약[3](PowerChek PRRSV (EU/NA) Real-time PCR Kit)');
insert into tblProduct values(343,'고위험성동물전염병유전검사용시약[3](PowerChek Salmonella gallinarum / Salmonella pullorum Real-time PCR Kit)');
insert into tblProduct values(344,'고위험성동물전염병유전검사용시약[3](PowerChekTM FMD Real-time PCR Kit,수출용)');
insert into tblProduct values(345,'고위험성동물전염병유전검사용시약[3](PowerChek Duck Hepatitis A Virus Real-time PCR Kit)');
insert into tblProduct values(346,'고위험성동물전염병유전검사용시약[3](PowerchekTM Fowl Adeno / CAV / MD Triplex Real-time PCR Kit)');
insert into tblProduct values(347,'고위험성동물전염병유전검사용시약[3](PowerChekTM CSFV Real-time PCR Kit,수출용)');
insert into tblProduct values(348,'고위험성동물전염병유전검사용시약[3](PowerChekTM ASFV Real-time PCR Kit Ver. 1.0, 수출용)');
insert into tblProduct values(349,'고위험성동물전염병유전검사용시약[3](virotype ASFV PCR Kit)');
insert into tblProduct values(350,'고위험성동물전염병유전검사용시약[3](PGB-D002TL POBGENTM Bee Pathogen Detection(BD-B2)_TaqMan Kit)');
insert into tblProduct values(351,'고위험성동물전염병유전검사용시약[3](Palm PCR™ ASFV Fast PCR Kit, 수출용)');
insert into tblProduct values(352,'고정형디지탈형엑스선진단투시촬영장치[3](수출용)(Clear Vision DR5000F)');
insert into tblProduct values(353,'동물진단용엑스선활영장치[2](MVX-56)');
insert into tblProduct values(354,'동물의료용고주파열상발생기[3](AK-F200-VET외 2건)');
insert into tblProduct values(355,'골겸자[1](Charriere 29-100외 33종)');
insert into tblProduct values(356,'골겸자[1](BCI1202 외 23종)');
insert into tblProduct values(357,'골겸자[1](IT07-0101-V외14종)');
insert into tblProduct values(358,'골겸자[1]');
insert into tblProduct values(359,'골접합용 나사[3](Orthopaedic bone screw for animal)');
insert into tblProduct values(360,'골절합용나사[3](1297 9 5100외 34종)');
insert into tblProduct values(361,'동물용 골접합용 나사[3](2.0LS-Ti64-20 외 1종)');
insert into tblProduct values(362,'동물용 골접합용 나사[3](200.1506-EU외 165종)');
insert into tblProduct values(363,'동물용 골접합용나사[3](200.1506-EC 외 201종)');
insert into tblProduct values(364,'골접합용나사[3](200.1004-EU 외 123종)');
insert into tblProduct values(365,'동물용골절합용나사[3](215-21004 외 210 종)');
insert into tblProduct values(366,'골절합용나사[3](VS403.010외 450종)');
insert into tblProduct values(367,'골접합용나사[3](1.5CO-21006-V 외 128종)');
insert into tblProduct values(368,'동물용골접합용나사[3](Bone Screw)');
insert into tblProduct values(369,'골절합용나사[3](T5411506외 24종)');
insert into tblProduct values(370,'골접합용나사[3](SCO1506 외 344종)');
insert into tblProduct values(371,'골접합용나사[3](SCO1506 외 344종)');
insert into tblProduct values(372,'골접합용나사[3](215-21004 외 210종)');
insert into tblProduct values(373,'골접합용나사[3](BAA.1504-EA 외 362종)');
insert into tblProduct values(374,'골절합용나사[3](BAB.1004-EA 외 120종)');
insert into tblProduct values(375,'골절합용나사[3](ARIX VET System Bone Screw Z12L-SO-004 외 215건)');
insert into tblProduct values(376,'골접합용나사[3](COS1606 외 32종)');
insert into tblProduct values(377,'골접합용와이어[3](Orthopaedic bone wire)');
insert into tblProduct values(378,'골접합용판[3](Orthopaedic fixation plate for animal)');
insert into tblProduct values(379,'골절합용판[3](129 99 0252외 11종)');
insert into tblProduct values(380,'동물용 골접합용 판[3](2.0LP-Ti-008외 1종)');
insert into tblProduct values(381,'동물용 골접합용 판[3](100.2004-TU 외 155종)');
insert into tblProduct values(382,'동물용 골접합용 판[3](120.2004-TU)');
insert into tblProduct values(383,'동물용 골접합용판[3](101.2004-SU 외 87종)');
insert into tblProduct values(384,'골접합용판[3](102.2004-SU-vet외 107종)');
insert into tblProduct values(385,'동물 골접합용 판[3](orthopedic fixation plate)');
insert into tblProduct values(386,'골접합용판[3](120.1006-SU외 87종)');
insert into tblProduct values(387,'동물용골접합용판[3](101-10003외 181 종)');
insert into tblProduct values(388,'골절합용판[3](VP4051.03외 301종)');
insert into tblProduct values(389,'골접합용판[3](2.0D-10004-V 외 110종)');
insert into tblProduct values(390,'동물용골접합용판[3](Bone Plate)');
insert into tblProduct values(391,'골절합용판[3](T7510003외 20종)');
insert into tblProduct values(392,'골접합용판[3](PSC1506 외 711종)');
insert into tblProduct values(393,'골접합용판[3](PSR1603 외 137종)');
insert into tblProduct values(394,'골접합용판[3](PSRD2408M 외 25종)');
insert into tblProduct values(395,'골접합용판[3](101-10003 외 191종)');
insert into tblProduct values(396,'골절합용판[3](AAA.2004-EU 외 179종)');
insert into tblProduct values(397,'골절합용판[3]((ABA.2004-EU 외 179종)');
insert into tblProduct values(398,'골절합용판[3](AAC.2004-EU 외 179종)');
insert into tblProduct values(399,'골절합용판[3](ABA.1204-SU 외 359종)');
insert into tblProduct values(400,'골절합용판[3](ARIX VET System Bone Plate Z12-ST-024-F 외 115건)');
insert into tblProduct values(401,'골접합용판[3](SPE1604 외 50종)');
